project:
  type: website
  output-dir: docs

website:
  title: "Nora Smith"
  favicon: ns_logo.png
  navbar:
    logo: ns_logo.png
    left:
      - href: index.qmd
        text: Home
      - About_Me.qmd
      - Interests.qmd
      - Relevant_Courses.qmd
      - Projects.qmd

format:
  html:
    theme: styles.scss
    mainfont: Inconsolata
    toc: true
    page-layout: full

editor: visual

