project:
  type: website
  output-dir: docs

website:
  title: "Nora Smith"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About_Me.qmd
      - Interests.qmd
      - Projects.qmd
      - Relevant_Courses.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    page-layout: full

editor: visual

