---
title: "Interests"
toc: FALSE
---

I couldn't decide on one of my interests to talk about, so I thought that I would briefly cover a few of them for y'all instead.

### Hockey

I grew up in San Jose during the San Jose Sharks "Golden Era," so how could I not love hockey. I got to grow up watching all of their playoff runs, year after year, and now comes the time that I get to watch them rebuild a new core with the hopes of reaching their next new generation of top tier players. I went to my first hockey game when I was a toddler, and cried over the shark head that the team skates out of, and I got a free SJ Sharkie plushie out of it. I also think that hockey is just one of the most interesting sports, since it's fast paced, you can see the plays develop, and you don't get super hot sitting out in the stands all day in the sun.

### Cooking

Another thing that I have been super into recently is cooking. I've always enjoyed baking, but I over the past year I've started finding more recipes online and making dinner for me and my friends. I realized that cooking and baking aren't too different, and cooking offers a lot more freedom since it doesn't have to be as exact as baking because a little bit too much of one ingredient isn't going to jeopardize how it cooks. I wanted to include some of the things that I've made recently, but I realized that I don't have any pictures of it. That being said, the last couple things I've made were: chicken tikka masala, creamy mushroom pasta, and a chili oil vodka sauce with pasta.

### Traveling

One of the things I wish I could do more, but can't right now given my schedule, is traveling. I used to travel a lot with my parents over the summer between the school years, and we went to some super cool places. I've been to London, Dublin, a few different cities in Italy, Austria, France, and more. I'm really hoping that after I graduate I'll get the chance to travel more. Some of the places that I haven't been, but would really like to visit are Amsterdam, Greece, and Spain.
