---
title: "Relevant Courses"
toc: FALSE
---

These are some of the courses that I've taken that have helped me expand my skill sets. I have included an example of a project from each course in the Projects tab of this site.

### GEOG W 12: Maps and Spatial Reasoning

This course introduced me to basic ArcGIS Pro concepts and what I could use it for, it helped create a foundation for me to build upon in later classes. I learned the basics of map abstraction, generalization, projections, and symbolization needed in order to create maps and use ArcGIS Pro to help me analyze spatial data.

### ENVS154: GIS for Environmental Applications

This course helped build on my previous class about ArcGIS Pro, diving deeper into how environmental researchers and professionals can use GIS in order to help analyze and communicate spatial patterns. I learned a lot about how to maps properly, and apply the skills I learned in order to create a StoryMap at the end of the course that analyzes how habitat corridors are impacted by various natural and anthropogenic threats.

### ENVS137: Conservation Planning

This course introduced me to Miradi, a program used to help streamline the conservation planning process. I learned how to identify fundamental objectives, features, indicators, and targets in a way that creates a cohesive conservation plan. I learned the ins and outs of the field, as well as got a feeling for mitigating some of the problems can often come up during the planning process. I got the opportunity to work on a real world project, and I worked with a group of 4 other people to help build a plan that will help increase the water resiliency of the Jalama Valley Ranch Property.

### ENVS193DS: Statistics for Environmental Studies 

This course has helped me gain confidence in my ability to analyze data and taught me valuable skills in RStudio. I now feel like I have a better handle on knowing which analytical tests to use in different situations, as well as being able to better convey the data I find through the plots and visualizations that I can make. This course has also helped me grow in my ability to interpret and contextualize the results I get from my analysis in both statistical and day-to-day dialect.
